/** Sumition Actions */
export const SEND_PRE_SUBMITION_DATA_REQUEST =
  'SEND_PRE_SUBMITION_DATA_REQUEST';
export const SEND_PRE_SUBMITION_DATA_REQUEST_SUCCESS =
  'SEND_PRE_SUBMITION_DATA_REQUEST_SUCCESS';
export const SEND_PRE_SUBMITION_DATA_REQUEST_FAILURE =
  'SEND_PRE_SUBMITION_DATA_REQUEST_FAILURE';
export const SEND_PRE_SUBMITION_DATA_REQUEST_AUTH_FAILURE =
  'SEND_PRE_SUBMITION_DATA_REQUEST_AUTH_FAILURE';
