/** Post Submition Actions */
export const GET_POST_SUBMITION_DATA_REQUEST =
  'GET_POST_SUBMITION_DATA_REQUEST';
export const GET_POST_SUBMITION_DATA_REQUEST_SUCCESS =
  'GET_POST_SUBMITION_DATA_REQUEST_SUCCESS';
export const GET_POST_SUBMITION_DATA_REQUEST_FAILURE =
  'GET_POST_SUBMITION_DATA_REQUEST_FAILURE';
export const GET_POST_SUBMITION_DATA_REQUEST_AUTH_FAILED =
  'GET_POST_SUBMITION_DATA_REQUEST_AUTH_FAILED';
